name: "Word to PDF Build, Release, and Deploy"
description: "Converts all DOCX files in a given folder to PDF, releases them as artifacts, and deploys to GitHub Pages."
inputs:
  root_folder:
    description: "The root folder containing DOCX files to be converted to PDF."
    required: true
  github_token:
    description: "GitHub token used for deployment."
    required: true

runs:
  using: "composite"
  steps:
    # Step 1: Checkout the Repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: Set up Git for committing changes
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    # Step 3: Extract the branch or tag name
    - name: Get Reference
      id: get_ref
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "REF_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "REF_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi
      shell: bash

    # Step 4: Install LibreOffice for DOCX to PDF Conversion
    - name: Install LibreOffice
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice
      shell: bash

    # Step 5: Convert All DOCX Files to PDF
    - name: Convert All DOCX Files to PDF
      run: |
        echo "Converting all DOCX files in the folder: ${{ inputs.root_folder }} to PDF"
        for docx_file in "${{ inputs.root_folder }}"/*.docx; do
          if [ -f "$docx_file" ]; then
            libreoffice --headless --convert-to pdf "$docx_file" --outdir "${{ inputs.root_folder }}"
            echo "Converted: $docx_file"
          fi
        done
        echo "Conversion finished, checking for output files."
        ls -la "${{ inputs.root_folder }}"
      shell: bash

    # Step 6: Verify PDF Generation
    - name: Verify PDF File Paths
      run: |
        for docx_file in "${{ inputs.root_folder }}"/*.docx; do
          if [ -f "$docx_file" ]; then
            output_pdf="${docx_file%.docx}.pdf"
            if [ -f "$output_pdf" ]; then
              echo "PDF file $output_pdf generated successfully."
            else
              echo "Error: PDF file $output_pdf not found after conversion."
              exit 1
            fi
          fi
        done
      shell: bash

    # Step 7: Upload All PDF Artifacts
    - name: Upload PDF Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: all-resumes-${{ env.REF_NAME }}
        path: "${{ inputs.root_folder }}/*.pdf"

    # Step 8: Prepare Directory for GitHub Pages
    - name: Prepare Directory for GitHub Pages
      run: |
        mkdir -p public/${{ env.REF_NAME }}
        for pdf_file in "${{ inputs.root_folder }}"/*.pdf; do
          if [ -f "$pdf_file" ]; then
            pdf_basename=$(basename "$pdf_file")
            mv "$pdf_file" "public/${{ env.REF_NAME }}/$pdf_basename"
          fi
        done
        echo "Directory prepared for GitHub Pages deployment:"
        ls -la public/${{ env.REF_NAME }}
      shell: bash

    # Step 9: Generate HTML Index File
    - name: Generate HTML Index
      run: |
        index_file="public/index.html"
        echo "<html><body><h1>Available Resumes</h1><ul>" > $index_file
        for dir in public/*/ ; do
          branch_name=$(basename "$dir")
          for pdf_file in "$dir"/*.pdf; do
            pdf_name=$(basename "$pdf_file")
            echo "<li><a href=\"./$branch_name/$pdf_name\">$pdf_name for $branch_name</a></li>" >> $index_file
          done
        done
        echo "</ul></body></html>" >> $index_file
        echo "HTML index generated at $index_file"
      shell: bash

    # Step 10: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./public
        keep_files: true
